# Generated by Django 3.0.4 on 2020-03-06 20:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200305_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='video_link',
            field=ckeditor.fields.RichTextField(default='dont forget link stream video'),
        ),
    ]
