# Generated by Django 3.0.4 on 2020-03-06 19:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200305_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='video_link',
            field=tinymce.models.HTMLField(default='remember about embeed video'),
        ),
    ]
