# Generated by Django 3.0.4 on 2020-03-07 13:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTo', models.DateTimeField(blank=True, null=True)),
                ('mostSignificantFigure', models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day'), ('hour', 'hour')], default='day', max_length=10)),
                ('numberOfFigures', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='video_link',
            field=ckeditor.fields.RichTextField(default='dont forget bout link'),
        ),
    ]
