# Generated by Django 3.0.4 on 2020-03-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200307_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimerFields',
        ),
        migrations.AddField(
            model_name='lead',
            name='dateTo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='mostSignificantFigure',
            field=models.CharField(choices=[('year', 'year'), ('month', 'month'), ('day', 'day'), ('hour', 'hour')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='numberOfFigures',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
    ]
